### ISSUE TITLE
Error message on npx execution: "new Octokit({headers}) is deprecated"

### ISSUE THREAD

**Issue by 07Gond** [cutenode/good-first-issue#107]
I just execute `npx good-first-issue` and find out this message:

![image](https://user-images.githubusercontent.com/2708687/53469088-a43cdb80-3a2a-11e9-8f90-f54412a469d1.png)

OS: MacOS Mojave 10.14.2
Node.js: 8.12.0
Npm: 6.4.1

**Comment by hemal7735** [comment]
@07Gond thank you for reporting the issue! I could reproduce that on my Mac.
![image](https://user-images.githubusercontent.com/13718176/53470047-5bb30b80-3a86-11e9-8b3b-73a963249f7d.png)

**Comment by hemal7735** [comment]
Okay, so I found out the issue. It is related to v0.24.0 when we were using `headers` which is not deprecated as part of new version of `@octokit/rest`. 
@bnb fixed that as part of https://github.com/bnb/good-first-issue/commit/c0d3b6c8ba53ca7ef623f482684918bd227ddf71#diff-72d460be7ab8987d776046e325845bb2  , but has not published the module with the fix.
@07Gond  Once he does that, it should fix the error.
**_Just to note:_** it is just a warning! It is not breaking any functionality.

**Comment by hemal7735** [comment]
verified that it is fixed with recent publish by @bnb
