### ISSUE TITLE
Depreciation warnings given by octokit when running on npx

### ISSUE THREAD

**Issue by co16353sidak** [cutenode/good-first-issue#110]
On running `good-first-issue` using `npx` and on selecting a package, `@octokit/rest` seems to give depreciation warnings on some of the modules used.

I have attached a screenshot below for your understanding.
<img width="1275" alt="Screenshot 2019-03-20 at 12 45 31 PM" src="https://user-images.githubusercontent.com/35738138/54665811-0eb6d800-4b0e-11e9-936a-967c2724e063.png">

I am also interested in working on this issue as my first contribution here. 🥇

**Comment by MoshiLi95** [comment]
Hi, I noticed another similar warning message, probably also due to `@octokit/rest` updates

Screen shot:
![91553117208_ pic_hd](https://user-images.githubusercontent.com/25776386/54720413-5c8f0880-4b2d-11e9-8a6d-e1b47552693d.jpg)

Could also swap `octokit.search.issues()` please

**Comment by ashokjayaprakash** [comment]
Hello @co16353sidak, I would like to work on this issue. Are you working on this issue currently ?

**Comment by hemal7735** [comment]
@bnb lot of issues related to octokit can be resolved by updating to new version. Can you help us understand how we are prioritizing this?

**Comment by bnb** [comment]
@hemal7735 I've not recently had time to work on this but if you'd like to open a PR I'd be happy to review 👍

**Comment by hemal7735** [comment]
@bnb #107 and this issue can be fixed by releasing the changes lying in the master branch.
reference: https://github.com/bnb/good-first-issue/commit/efd9860263aa18abbe1db4ab249b90decc130737#diff-72d460be7ab8987d776046e325845bb2R28
Can you publish the changes?

**Comment by hemal7735** [comment]
verified that it is fixed with recent publish by @bnb
