### ISSUE TITLE
Use kleur instead of chalk

### ISSUE THREAD

**Issue by DanielRuf** [cutenode/good-first-issue#138]
`kleur` is generally faster and smaller so we can replace `chalk`.

**Comment by dhuang612** [comment]
I will work on this!

**Comment by dhuang612** [comment]
Hey Daniel,
so I swapped chalk out for kleur and was running npm test when I got the following fail
<img width="769" alt="Screen Shot 2019-09-04 at 3 57 27 PM" src="https://user-images.githubusercontent.com/49162249/64287114-dd4f8e80-cf2c-11e9-83e0-77eb8fd66e6e.png">
I was hoping to get some advice on what to do next?

Thanks!
