### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by DanielRuf** [cutenode/good-first-issue#142]
There are a "few" branches which can be deleted:

https://github.com/cutenode/good-first-issue/branches/all

**Comment by dhuang612** [comment]
Hi,

I would like to take this on

**Comment by DanielRuf** [comment]
@8671584 you are free to work on it.

**Comment by DanielRuf** [comment]
@dhuang612 you are free to work on it.

**Comment by DanielRuf** [comment]
@dhuang612 feel free to work on it.

**Comment by dhuang612** [comment]
Hey,
I've done some research into this and I don't understand how I'm supposed to delete these stale branches.
When I run git branch -a 
I see a giant list of branches 

but then when I try to do 
git branch -d greenkeeper/@octokit/rest-16.20.0
for ex
it returns
error: branch 'greenkeeper/@octokit/rest-16.20.0' not found.

I was hoping I could get some help on this.

Thanks!

**Comment by DanielRuf** [comment]
You can delete with `git push -d` to delete a remote branch. Or do it in the GitHub UI.

**Comment by DanielRuf** [comment]
You can do that only with the right org permissions.

**Comment by dhuang612** [comment]
I don't believe I have the correct permissions setup for me to delete from the github gui?

**Comment by DanielRuf** [comment]
Exactly.

**Comment by dhuang612** [comment]
so, I can't complete this?

**Comment by DanielRuf** [comment]
Exactly, you can not unless you are a collaborator with write permissions.
