### ISSUE TITLE
Add descriptions to projects in data/projects.json

### ISSUE THREAD

**Issue by bnb** [cutenode/good-first-issue#53]
We currently support including descriptions in `projects.json` and consuming them (at least in the CLI – not entirely sure about the module), but don't currently have any descriptions.

Before we get a tremendous amount of projects, it would be incredible to get descriptions and require them when adding new ones so we don't have to do a bunch retroactively 👍

**Comment by hemal7735** [comment]
Maybe `good-first-issue` or `help-wanted`? 🤔

**Comment by bnb** [comment]
@hemal7735 for this issue? I +1 that 👍

**Comment by boneskull** [comment]
could you not pull descriptions from `description` prop of `octokit.repos.get()`?

**Comment by hemal7735** [comment]
@boneskull that is great, would you like to contribute?
@bnb Are we planning to show description in the console?

**Comment by bnb** [comment]
@hemal7735 it's currently displayed in the project selector when you run `good-first-issue` without a project argument. We should also augment the `lib/log.js` output to surface the descriptions.

**Comment by aashimawadhwa** [comment]
can you please explain the issue more elaborately
