### ISSUE TITLE
Long title messes the UI 

### ISSUE THREAD

**Issue by ItamarShDev** [cutenode/good-first-issue#56]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/953371/48923192-2d38f980-eeb5-11e8-8a99-028ffac5d9e3.png">

**Comment by bnb** [comment]
Yup, I've seen this before. It really depends on the width of your terminal. We could theoretically split up the title if it exceeds a certain number of characters 🤔

**Comment by ItamarShDev** [comment]
I can apply the fix, once I'll know what the decided fix is :)

**Comment by bnb** [comment]
@ItamarShDev feel free to take a stab at whatever you think would work! My thoughts:

- We add custom padding + a string that total 19 characters when the title is the longest line (see [this screenshot](https://user-images.githubusercontent.com/502396/48986194-ed098f00-f0df-11e8-9ae9-dc248df9e240.png))
- I would suggest we use 80 characters as a good place to cap
- 80 - 19 = 61

Suggestion: 
- If a title exceeds 61 characters, split it at the ` ` (space) before the 69th character
- Start the rest of the title on the same character as the first letter of the rest of the title so they are aligned (I believe this will always be character 16, but keep in mind 4 characters that are added by Boxen)

**Comment by DanielRuf** [comment]
Hm, why not use `cli-table3`?

**Comment by DanielRuf** [comment]
Hm, why not use `cli-table3`? Or we should report this in the `boxen` repo.
